server:
  port: 8080
keycloak:
  #URL du serveur keycloak sur lequel notre application doit se connecter.
  auth-server-url: http://localhost:8081/auth
  #Realm dédié a notre application
  realm: Projet
  #Nom du client tel que défini dans keycloak
  resource: front
  #Permet à notre application de se connecter sans authentification.
  public-client: true
  #Défini le nom d'utilisateur keycloak comme nom de principal dans spring.
  principal-attribute: preferred_username

spring:
  application:
    name: front

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

